name: Generate All Game Contribution Graphs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Pacman
        uses: lowlighter/metrics@latest
        with:
          filename: pacman-contribution-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pacman: yes
          plugin_pacman_user: pradhanashwarya2122
          plugin_pacman_animation: yes
      
      - name: Upload Pacman
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: pacman-output
          keep_files: true

  generate-bomberman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Bomberman
        uses: lowlighter/metrics@latest
        with:
          filename: bomberman-contribution-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pacman: yes
          plugin_pacman_user: pradhanashwarya2122
          plugin_pacman_animation: yes
          plugin_pacman_game: bomberman
      
      - name: Upload Bomberman
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: pacman-output
          keep_files: true

  generate-galaga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Galaga
        uses: lowlighter/metrics@latest
        with:
          filename: galaga-contribution-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pacman: yes
          plugin_pacman_user: pradhanashwarya2122
          plugin_pacman_animation: yes
          plugin_pacman_game: galaga
      
      - name: Upload Galaga
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: pacman-output
          keep_files: true
